import Head from "next/head";
import SectionBanner from "@/components/sectionBanner";
import Link from "next/link";
import Image from "next/image";

export default function Home({ latestThreePosts }) {

	const skills = ["HTML", "CSS", "JavaScript", "React.js", "Next.js", "jQuery", "SASS", "Git", "Gulp", "WordPress", "Bootstrap", "Tailwind CSS"];

	return (
		<>
			<Head>
				<title>About - Geoff Hignett - Front End Web Developer</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<SectionBanner title="about" />
            <div className="max-w-theme mx-auto flex flex-col lg:flex-row justify-between py-10 lg:py-20 px-3">
                <div className="w-full lg:w-1/2 lg:pr-10 mb-10">
					<h2 className="text-xl font-bold mb-3">Who I am</h2>
					<p className="font-poppins">I'm a Frontend Web Developer building the Front-end of Websites and Web Applications that leads to the success of the overall product. Check out some of my work in the Projects section.</p>
					<p className="font-poppins">I also like sharing content related to the stuff that I have learned over the years in Web Development so it can help other people of the Dev Community. Feel free to Connect or Follow me on my</p>
					<p className="font-poppins">I'm open to Job opportunities where I can contribute, learn and grow. If you have a good opportunity that matches my skills and experience then don't hesitate to contact me.</p>
				</div>
                <div className="w-full lg:w-1/2 lg:pl-10">
					<h2 className="text-xl font-bold mb-3">My Skills</h2>
					<ul>
						{skills.map((skill, index) => (
							<li key={index} className="font-poppins font-bold p-5 bg-slate-200 rounded-xl inline-block m-2">
								{skill}
							</li>
						))}
					</ul>
				</div>
			</div>


		</>
	);
}